services:
  python:
    container_name: ${PYTHON_CONTAINER_HOST}
    hostname: ${PYTHON_HOST}
    env_file: .env
    tty: true
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 8808:8808
    volumes:
      - ./src:/python/src/app